#!/bin/bash

echo "🚀 Deploying Blackjack Vision Backend to Render"
echo "==============================================="

echo "📋 Manual Deployment Steps for Render:"
echo ""
echo "1. Go to https://render.com and sign up/login"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository or upload files"
echo "4. Configure the service:"
echo "   - Name: blackjack-vision-backend"
echo "   - Environment: Docker"
echo "   - Region: Choose closest to you"
echo "   - Branch: main (or your current branch)"
echo "   - Build Command: (leave empty for Docker)"
echo "   - Start Command: (leave empty for Docker)"
echo ""
echo "5. Advanced Settings:"
echo "   - Auto-Deploy: Yes"
echo "   - Health Check Path: /health"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "📁 Files already prepared for Render deployment:"
echo "✅ backend/Dockerfile - Ready for deployment"
echo "✅ backend/render.yaml - Render configuration"
echo "✅ backend/start.sh - Start script"
echo "✅ backend/main.py - Updated with PORT support"
echo ""
echo "🔗 After deployment, you'll get a URL like:"
echo "https://blackjack-vision-backend.onrender.com"
echo ""
echo "📝 Next steps after deployment:"
echo "1. Copy your actual Render URL"
echo "2. Update frontend/lib/config/api_config.dart"
echo "3. Run ./deploy_frontend.sh"
echo ""
echo "🧪 Test your deployed backend:"
echo "curl https://your-render-url.onrender.com/health"
