#!/bin/bash

echo "🔄 Redeploying Backend with Marked Contours Feature"
echo "=================================================="

echo "📝 Changes made:"
echo "✅ Added /analyze/marked-contours/ endpoint"
echo "✅ Added create_marked_contours_image() function"
echo "✅ Added base64 image encoding support"
echo ""
echo "🚀 To redeploy your backend:"
echo ""
echo "Option 1: Render (Automatic)"
echo "1. Go to https://render.com/dashboard"
echo "2. Find your 'blackjack-vision-backend' service"
echo "3. Click 'Manual Deploy' → 'Deploy latest commit'"
echo "4. Wait 3-5 minutes for deployment"
echo ""
echo "Option 2: Manual Upload"
echo "1. Download your updated backend folder"
echo "2. Re-upload to your hosting service"
echo "3. Restart the service"
echo ""
echo "🧪 Test the new endpoint:"
echo "curl -X POST https://blackjack-vision-backend.onrender.com/analyze/marked-contours/ \\"
echo "  -F 'file=@your-image.jpg' \\"
echo "  -F 'players=1'"
echo ""
echo "📱 Then redeploy frontend:"
echo "./deploy_frontend.sh"
